name-template: 'TYPO3 Coding Standards Package $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH-dev'
prerelease: true
version-resolver:
  default: minor
filter-by-commitish: true
template: _⚠⚠⚠ Draft - will be overwritten with the next release ⚠⚠⚠_
